# Generated by Django 3.2.5 on 2021-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_app', '0003_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(default='Active', max_length=200),
        ),
    ]
