# Generated by Django 3.2.5 on 2021-09-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tick_app', '0004_resource_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P1 (Critical)', 'P1 (Critical)'), ('P2 (High)', 'P2 (High)'), ('P3 (Medium)', 'P3 (Medium)'), ('P4 (Low)', 'P4 (Low)'), ('P5 (Info)', 'P5 (Info)')], max_length=16)),
                ('short_desc', models.CharField(max_length=20)),
                ('long_desc', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tick_app.queue')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tick_app.resource')),
            ],
        ),
    ]
