# Generated by Django 3.2.5 on 2021-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_app', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Resolved', 'Resolved'), ('Abandoned', 'Abandoned'), ('Info required', 'Info required'), ('Updated', 'Updated')], default='New', max_length=16),
        ),
    ]
