# Generated by Django 3.2.5 on 2021-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_app', '0006_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='short_desc',
            field=models.CharField(max_length=50),
        ),
    ]
