# Generated by Django 3.2.5 on 2021-09-23 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tick_app', '0009_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
