# Generated by Django 3.2.5 on 2021-09-23 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tick_app', '0010_queue_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
        migrations.AddField(
            model_name='queue',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
