# Generated by Django 3.2.5 on 2021-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_app', '0011_auto_20210923_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_engineer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
