# Generated by Django 3.2.5 on 2021-09-24 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tick_app', '0012_ticket_assigned_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Resolved', 'Resolved'), ('Abandoned', 'Abandoned'), ('Info required', 'Info required'), ('Updated', 'Updated'), ('Active', 'Active')], default='New', max_length=16),
        ),
    ]
